Enrollment no.: 240840116041

## Practical-3 | Apply fltering, sorting, aggregation, and GroupBy operations on real-world datasets.

**Step:1 Import library**

In [ ]:
# Import library
import pandas as pd

In [ ]:
# Create employee dataset
data ={
    "Emp_Id":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

In [ ]:
# Convert data into DataFrame
df = pd.DataFrame(data)
df

   Emp_Id   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step:2 Filtter Data**

In [ ]:
# Filter employees from IT department
df[df['Department']=="IT"]

   Emp_Id   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

In [ ]:
# Filter employees from Surat city
df[df['City']=="Surat"]

   Emp_Id   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

In [ ]:
# Filter IT employees having salary more than 50000
df[(df["Department"]=="IT")&(df["Salary"]>50000)]
#Both conditions must be True:
#1. Department must be "IT"
#2. Salary must be greater than 50,000

   Emp_Id   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step:3 Sort Data**

In [ ]:
# Sort data according to salary
df.sort_values(by="Salary")

   Emp_Id   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

In [ ]:
# Sort salary from highest to lowest
df.sort_values(by="Salary",ascending=False)

   Emp_Id   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

In [ ]:
# Sort data by department and salary
df.sort_values(by=["Department","Salary"], ascending=[True,False])

   Emp_Id   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step:4 Perfrom Aggregation**

In [ ]:
# Find total salary
df["Salary"].sum()

np.int64(376000)

In [ ]:
# Find average salary
df["Salary"].mean()

np.float64(47000.0)

In [ ]:
# Find highest salary
df["Salary"].max()

60000

In [ ]:
# Find lowest salary
df["Salary"].min()

38000

In [ ]:
# Count total employees
df["Emp_Id"].count()

np.int64(8)

**Step:5 Perfrom Group By Operation**

In [ ]:
# Find average salary of each department
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

In [ ]:
# Find minimum salary of each department
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

In [ ]:
# Count employees in each department
df.groupby("Department")["Emp_Id"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_Id, dtype: int64

In [ ]:
# Find maximum salary of each department
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

**Step:6 Multiple Aggerration Function**

In [ ]:
# Find count, total, average, minimum and maximum salary
# for each department
df.groupby("Department")["Salary"].agg(["count","sum","mean","min","max"])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step:7 Save Your Result**

In [ ]:
# Save the employee data into CSV file
df.to_csv("Employee_Data.csv",index=False)
# Show message after creating the dataset
print("Dataset create successfully.")

Dataset create successfully.

**Step:8 Download Dataset**

In [ ]:
# Save the data into CSV file
df.to_csv("Employee_Data.csv",index=False)
# Import files library from Google Colab
from google.colab import files
# Download the CSV file
files.download("Employee_Data.csv")