Practical-2 | Perfrom data inspection, cleaning, handling missing values duplicate removal, and data transformation using pandas.

Step:1 Import Pandas library

In [ ]:
# Import the Pandas library
import pandas as pd

Step:2 Create Simple Dataset

In [ ]:
# Create a dictionary containing student data
data = {
    "ID":[101, 102, 103, 104, 104, 105, 106, 107],
    "Name" :["Rahu", "priya", "Amit", None, "Riya", "Ajay", " Naresh", "Jenil"],
    "Age" :[20, 21, None, 20, 20, 22, 23, 28],
    "City" :["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks" : [85, None, 78, 88, 88, 81, 90, 93]
}

In [ ]:
# Create a DataFrame from the data
df = pd.DataFrame(data)
# Display dataframe
df

    ID     Name   Age       City  Marks
0  101     Rahu  20.0      Surat   85.0
1  102    priya  21.0    Navsari    NaN
2  103     Amit   NaN      Surat   78.0
3  104     None  20.0    Bharuch   88.0
4  104     Riya  20.0    Bharuch   88.0
5  105     Ajay  22.0    Navsari   81.0
6  106   Naresh  23.0      Surat   90.0
7  107    Jenil  28.0  Ahmedabad   93.0

Step:3 Inspect the dataset

In [ ]:
# Display the first five rows of the dataset.
df.head()

    ID   Name   Age     City  Marks
0  101   Rahu  20.0    Surat   85.0
1  102  priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [ ]:
# Display the last five rows of the dataset.
df.tail()

    ID     Name   Age       City  Marks
3  104     None  20.0    Bharuch   88.0
4  104     Riya  20.0    Bharuch   88.0
5  105     Ajay  22.0    Navsari   81.0
6  106   Naresh  23.0      Surat   90.0
7  107    Jenil  28.0  Ahmedabad   93.0

In [ ]:
# Display detailed information about the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
# Display Statistical Information for numerical columns.
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [ ]:
# Display the dimensions of the dataset.
df.shape

(8, 5)

In [ ]:
#Display the data types of each columns.
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [ ]:
# Display all the column of the dataframe.
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step:4 Check Missing Values

In [ ]:
# Check for missing (null) values in every column.
df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [ ]:
# count null values for each column.
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [ ]:
# count total number of null values.
df.isnull().sum().sum()

np.int64(3)

Step:5 Fill Missing Values

In [ ]:
#replace missing values in the marks column.
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

    ID     Name   Age       City      Marks
0  101     Rahu  20.0      Surat  85.000000
1  102    priya  21.0    Navsari  86.142857
2  103     Amit   NaN      Surat  78.000000
3  104     None  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

In [ ]:
# replace missing values in the age column.
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID     Name   Age       City      Marks
0  101     Rahu  20.0      Surat  85.000000
1  102    priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104     None  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

In [ ]:
# replacing missing name with the text "unknown".
df["Name"] = df["Name"].fillna("unknown")
df

    ID     Name   Age       City      Marks
0  101     Rahu  20.0      Surat  85.000000
1  102    priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

STep:6 Setect Duplicate records

In [ ]:
# Check whether each raw is duplicated.
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
# count the total number of duplicate rows.
df.duplicated().sum()

np.int64(0)

Step:7 Remove Duplicate Records

In [ ]:
df.drop_duplicates()
df

    ID     Name   Age       City      Marks
0  101     Rahu  20.0      Surat  85.000000
1  102    priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

Step:8 Rename a column

In [ ]:
# rename the column "Marks" to "score".
df.rename(columns={"Marks":"Score"}, inplace=True)
# Display the DataFrame
df

    ID     Name   Age       City      Score
0  101     Rahu  20.0      Surat  85.000000
1  102    priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

Step:9 change Data Type

In [ ]:
# cover the Age column from float  to integer.
df.astype({"Age":"int64"}).dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Step:10 Create a New column

In [ ]:
# Create a new column called "Final Score"
# Add 5 marks to the Score column
df["Final Score"]=df["Score"]+5
df

    ID     Name   Age       City      Score  Final Score
0  101     Rahu  20.0      Surat  85.000000    90.000000
1  102    priya  21.0    Navsari  86.142857    91.142857
2  103     Amit  22.0      Surat  78.000000    83.000000
3  104  unknown  20.0    Bharuch  88.000000    93.000000
4  104     Riya  20.0    Bharuch  88.000000    93.000000
5  105     Ajay  22.0    Navsari  81.000000    86.000000
6  106   Naresh  23.0      Surat  90.000000    95.000000
7  107    Jenil  28.0  Ahmedabad  93.000000    98.000000

Step:11 Convert Text To UpperCase

In [ ]:
# Convert all names to uppercase
df["Name"]=df["Name"].str.upper()
df

    ID     Name   Age       City      Score  Final Score
0  101     RAHU  20.0      Surat  85.000000    90.000000
1  102    PRIYA  21.0    Navsari  86.142857    91.142857
2  103     AMIT  22.0      Surat  78.000000    83.000000
3  104  UNKNOWN  20.0    Bharuch  88.000000    93.000000
4  104     RIYA  20.0    Bharuch  88.000000    93.000000
5  105     AJAY  22.0    Navsari  81.000000    86.000000
6  106   NARESH  23.0      Surat  90.000000    95.000000
7  107    JENIL  28.0  Ahmedabad  93.000000    98.000000

Step:12 Covert Text To LowerCase

In [ ]:
# Convert all city names to lowercase
df["City"]=df["City"].str.lower()
df

    ID     Name   Age       City      Score  Final Score
0  101     RAHU  20.0      surat  85.000000    90.000000
1  102    PRIYA  21.0    navsari  86.142857    91.142857
2  103     AMIT  22.0      surat  78.000000    83.000000
3  104  UNKNOWN  20.0    bharuch  88.000000    93.000000
4  104     RIYA  20.0    bharuch  88.000000    93.000000
5  105     AJAY  22.0    navsari  81.000000    86.000000
6  106   NARESH  23.0      surat  90.000000    95.000000
7  107    JENIL  28.0  ahmedabad  93.000000    98.000000

Step:13 Remove Extra Spaces

In [ ]:
# Remove extra spaces from the City column
df["City"] = df["City"].str.strip()
df

    ID     Name   Age       City      Score  Final Score
0  101     RAHU  20.0      surat  85.000000    90.000000
1  102    PRIYA  21.0    navsari  86.142857    91.142857
2  103     AMIT  22.0      surat  78.000000    83.000000
3  104  UNKNOWN  20.0    bharuch  88.000000    93.000000
4  104     RIYA  20.0    bharuch  88.000000    93.000000
5  105     AJAY  22.0    navsari  81.000000    86.000000
6  106   NARESH  23.0      surat  90.000000    95.000000
7  107    JENIL  28.0  ahmedabad  93.000000    98.000000

Step:14 sort the dataset

In [ ]:
# Sort the DataFrame based on the "Final Score" column
# ascending=False sorts the values from highest to lowest
df.sort_values(by="Final Score", ascending=False)
df

    ID     Name   Age       City      Score  Final Score
0  101     RAHU  20.0      surat  85.000000    90.000000
1  102    PRIYA  21.0    navsari  86.142857    91.142857
2  103     AMIT  22.0      surat  78.000000    83.000000
3  104  UNKNOWN  20.0    bharuch  88.000000    93.000000
4  104     RIYA  20.0    bharuch  88.000000    93.000000
5  105     AJAY  22.0    navsari  81.000000    86.000000
6  106   NARESH  23.0      surat  90.000000    95.000000
7  107    JENIL  28.0  ahmedabad  93.000000    98.000000

Step:15 Save the cleaned dataset

In [ ]:
# Save the cleaned df as a new csv file
df.to_csv("cleaned_student.csv", index=False)

# Display a success message
print("Dataset saved Successfully.")

Dataset saved Successfully.