Enrollment No.: 240840116041

**Practical 1 | Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON ƒles using Pandas.**

**Step:1 Import Pandas Liberary**

In [ ]:
# Step 1: Import the Pandas library
import pandas as pd

**Step:2 create simple data**

In [ ]:
# Store student details such as ID, Name, Age, City and Marks
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krishna", "Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahmedabad"],
    "Marks": [85, 92, 78, 88, 81, 84, 90]
}

**Step:3 create dataframe**

In [ ]:
# DataFrame stores the data in rows and columns
df = pd.DataFrame(data)
df

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:4 save data as csv file **

In [ ]:
# index=False prevents saving the row numbers
df.to_csv("students.csv", index=False)
print("CSV file created successfully.")

CSV file created successfully.

**Step:5 save data as excel file **

In [ ]:
# Creates an Excel file containing the student data
df.to_excel("students.xlsx", index=False)
print("Excel file created successfully.")

Excel file created successfully.

**Step:6 save data as json file**

In [ ]:
# orient="records" stores each row as a separate record
# indent=4 makes the JSON file easy to read
df.to_json("students.json", orient="records", indent=4)
print("JSON file created successfully.")

JSON file created successfully.

**Step:7 read the csv file**

In [ ]:
# Load the CSV file into a DataFrame
df_csv = pd.read_csv("students.csv")
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:8 read the excel file**

In [ ]:
# Load the Excel file into a DataFrame
df_excel = pd.read_excel("students.xlsx")
df_excel

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:9 read the json file**

In [ ]:
# Load the JSON file into a DataFrame
df_json = pd.read_json("students.json")
df_json

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:10 Display the first five records**

In [ ]:
# head() displays the first 5 rows by default
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**Step:11 Display The last five records**

In [ ]:
# tail() displays the last 5 rows by default
df_csv.tail()

    ID     Name  Age         City  Marks
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:12 Display Dataset Information**

In [ ]:
# info() shows columns, data types and non-null values
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**Step:13 Display Statistical Summary**

In [ ]:
# describe() gives count, mean, minimum, maximum and other statistics
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

**Step:14 Display Dataset Shape**

In [ ]:
# shape returns the number of rows and columns
df_csv.shape

(7, 5)

**Step:15 display Column Names**

In [ ]:
# columns shows all column names in the dataset
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step:16 Display Data Types**

In [ ]:
# dtypes shows the data type of each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step:17 Check for Missing Values**

In [ ]:
# isnull() finds missing values
# sum() counts the missing values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step:18 Display a Single Column**

In [ ]:
# Select only the City column
df_csv["City"]

0          Surat
1        Navsari
2         Valsad
3        Bharuch
4          Surat
5    Gandhinagar
6      Ahmedabad
Name: City, dtype: object

**Step:19 Display Multiple Columns**

In [ ]:
# Select Name and Marks columns
df_csv[["Name", "Marks"]]

      Name  Marks
0    Rahul     85
1    Priya     92
2     Amit     78
3     Riya     88
4    Karan     81
5  Krishna     84
6    Harry     90

**Step:20 Filter Record**

In [ ]:
# Display only students whose marks are greater than 80
df_csv[df_csv["Marks"] > 80]

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

**Step:21 Calculate Average Marks**

In [ ]:
# mean() calculates the average of the Marks column
df_csv["Marks"].mean()

np.float64(85.42857142857143)

**Step:22 Short Data**

In [ ]:
# Sort students according to Marks
# ascending=False sorts from highest to lowest
df_csv.sort_values(by="Marks", ascending=False)

    ID     Name  Age         City  Marks
1  102    Priya   21      Navsari     92
6  107    Harry   28    Ahmedabad     90
3  104     Riya   20      Bharuch     88
0  101    Rahul   20        Surat     85
5  106  Krishna   24  Gandhinagar     84
4  105    Karan   22        Surat     81
2  103     Amit   19       Valsad     78

**Step:23 Display Dataset**

In [ ]:
# Display all records of the DataFrame
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        Surat     85
1  102    Priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    Karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90